### ISSUE TITLE
Add Checklist for Transferring Repositories

### ISSUE THREAD

**Issue by prikhi** [elm-community/Manifesto#73]
I think it'd be useful process-wise if people interested in transferring ownership to elm-community could copy & paste a checklist from the Manifesto into their PR to help track the progress & make sure all the bases have been covered. This comes from seeing the following pasted into pretty much every PR:

```
delete all the tags the repo currently has
reset the elm-package.json file to 1.0.0
make sure the elm-package.json points to elm-community/typed-svg
publish as 1.0.0
```

I would push something, but just want to check-in with members about what the list should include.

I'm thinking something like:

- [x] Create PR Adding the New Repository & Maintainer to `maintainers.md`
- [ ] Maintainer Has Been Made an Elm-Community Member & Part of Maintainers Group
- [ ] An Elm-Community Repository Has Been Created
- [ ] Original Package Owner Has Forked Elm-Community Repo Back to their Account
- [ ] All Tags From the Elm-Community Repository & Maintainers Local Repository Have Been Deleted
- [ ] Repository in `elm-package.json` Has Been Changed & Version Set to `1.0.0`
- [ ] New `1.0.0` Tag Has Been Added
- [ ] Code & Tag Have Been Pushed to Elm-Community Repository
- [ ] Elm-Community Package Has Been Published
- [ ] PR Has Been Merged

Pinging @eeue56 & @mgold as you're frequently the people that merge transfer requests. Feel free to close this if you think it's unecessary.

**Comment by eeue56** [comment]
Yes this is a good idea and I've been meaning to do it for a while. Not in the mood atm the review this but I will when I get a chance.

**Comment by eeue56** [comment]
Made in this: https://github.com/elm-community/Manifesto/new/master thanks!

**Comment by prikhi** [comment]
Yup, no problem. Although I was imagining it living in the `Moving a Repo to Elm-Community` section of the README(along with some text like `Please include the following checklist in your Pull Request:`). But if that's adding too much text, maybe include a link to the new file at the end of that section?

And it'd be helpful for it to be in code tags for easy copy & pasting into a PR:
```
- [x] Create PR Adding the New Repository & Maintainer to `maintainers.md`
- [ ] Maintainer Has Been Made an Elm-Community Member & Part of Maintainers Group
- [ ] An Elm-Community Repository Has Been Created
- [ ] Original Package Owner Has Forked Elm-Community Repo Back to their Account
- [ ] All Tags From the Elm-Community Repository & Maintainers Local Repository Have Been Deleted
- [ ] Repository in `elm-package.json` Has Been Changed & Version Set to `1.0.0`
- [ ] New `1.0.0` Tag Has Been Added
- [ ] Code & Tag Have Been Pushed to Elm-Community Repository
- [ ] Elm-Community Package Has Been Published
- [ ] PR Has Been Merged
```

But those are just nitpicks, since I don't have the power to accept ownership transfer requests I'm fine with whatever process/layout works best for you.

**Comment by eeue56** [comment]
Yeah, I thought about that. But in the the past, when I've used checklists like that, I've found it hard to copy and paste when it gets bigger on some devices. This way we can just grab `raw` and copy and paste it as-is :)

**Comment by fredcy** [comment]
I'm confused by the third step, "An Elm-Community Repository Has Been Created". Shouldn't that be something more like "Move the existing repo from personal account to elm-community".
